### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by jelinekp** [google-developer-training/basic-android-kotlin-compose-training-cupcake#17] opened 2022-11-13 05:09 UTC
In starter code of the Cupcake app, there is no "currentScreen" parameter in "@Composable
fun CupcakeAppBar" in java/com/example/cupcake/CupcakeScreen.kt
The text value of the TopAppBar title is hardcoded.
Therefore, it's hard to understand the step "7" in the pathway, because according to the tutorial, the existence of "currentScreen" parameter is expected. Also the text of the tutorial is a bit ambiguous. You don't know whether is CupcakeAppBar composable or CupcakeAppBar call in CupcakeApp composable meant.
![image](https://user-images.githubusercontent.com/17750588/201506749-287ffa4b-7681-4384-ab94-c9f7b9c49103.png)

**Comment by osuleymanova** [comment] 2022-11-17 00:17
Duplicate of #10

**Comment by osuleymanova** [comment] 2023-01-09 20:47
Hello @jelinekp,

Thanks for reaching out to us and sharing your concern. The steps are updated:

![Screenshot 2023-01-09 at 12 42 48 PM](https://user-images.githubusercontent.com/86437155/211404500-c265e076-66bc-4d50-83f4-19046ec923f5.png)

Please feel free to re-open the ticket, if the text of the tutorial is still unclear.

**Closed by osuleymanova** 2023-01-09 20:47 UTC
