### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by dev-xero** [google-developer-training/basic-android-kotlin-compose-training-cupcake#38] opened 2023-02-18 13:10 UTC
There's a **small mistake** in the docs, in this code, the title property stringResource id should be `currentScreen.title`

```kotlin
TopAppBar(
   title = { Text(stringResource(currentScreen.)) },
   modifier = modifier,
   navigationIcon = {
       if (canNavigateBack) {
           IconButton(onClick = navigateUp) {
               Icon(
                   imageVector = Icons.Filled.ArrowBack,
                   contentDescription = stringResource(R.string.back_button)
               )
           }
       }
   }
)
```
This code is missing the 'title' property at the end of the `stringResource(currentScreen)`.  
It should be: 
```kotlin
TopAppBar(
   title = { Text(stringResource(currentScreen.title)) },
   modifier = modifier,
   navigationIcon = {
       if (canNavigateBack) {
           IconButton(onClick = navigateUp) {
               Icon(
                   imageVector = Icons.Filled.ArrowBack,
                   contentDescription = stringResource(R.string.back_button)
               )
           }
       }
   }
)

**Comment by osuleymanova** [comment] 2023-04-05 22:18
Duplicate of #31, #17, #10

**Closed** 2023-04-07 11:09 UTC
