### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by edapess** [google-developer-training/basic-android-kotlin-compose-training-cupcake#39] opened 2023-02-21 13:23 UTC
in ```Add button handlers to OrderSummaryScreen``` 
in ```2.Add another parameter of type (String, String) -> Unit with a default value of {} and name this one onSendButtonClicked.```

```@Composable
fun OrderSummaryScreen(
    orderUiState: OrderUiState,
    onCancelButtonClicked: () -> Unit = {},
    onSendButtonClicked: (String, String) -> Unit = {},
    modifier: Modifier = Modifier
){
    ...
}
```

change signature of lambda expression  
```onSendButtonClicked: (String, String) -> Unit = {}```
 to 
```onSendButtonClicked: (String, String) -> Unit = { s: String, s1: String -> }```

**Comment by osuleymanova** [comment] 2023-04-05 22:17
Duplicate of #36

**Comment by johnshea** [comment] 2023-06-21 18:11
Hi @edapess 

Thank you for reporting this issue.

The lesson is being updated to address it and will be republished in the near future.

Hope you are enjoying the course!

Regards.

**Closed by johnshea** 2023-06-21 18:11 UTC
