### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose -> Incorrect parameters passed to cupcakeNavHost_verifyStartDestination() {assertEquals()}

### ISSUE THREAD

**Issue by SergioTellezSanchez** [google-developer-training/basic-android-kotlin-compose-training-cupcake#21] opened 2022-11-17 18:01 UTC
![image](https://user-images.githubusercontent.com/49140286/202521994-c06a10fc-77b9-43a6-b51f-9780996b2020.png)

Correct:

    fun cupcakeNavHost_verifyStartDestination() {
        assertEquals(CupcakeScreen.Start.name, navController.currentBackStackEntry?.destination?.route)
    }

**Comment by osuleymanova** [comment] 2022-11-17 22:25
Duplicate of #7

**Comment by osuleymanova** [comment] 2022-11-18 18:40
@SergioTellezSanchez 
Thank you for contacting us and sharing your feedback. The code snippet in the codelab has been recently updated so no more errors should be observed:

![Screen Shot 2022-11-18 at 10 39 53 AM](https://user-images.githubusercontent.com/86437155/202778817-6aa18244-881c-4446-8702-d933bbae467c.png)

**Closed by osuleymanova** 2022-11-18 18:40 UTC
